# Generated by Django 4.0.4 on 2022-05-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(blank=True, max_length=100, null=True)),
                ('total_cases', models.CharField(blank=True, max_length=100, null=True)),
                ('total_deaths', models.CharField(blank=True, max_length=100, null=True)),
                ('recovered', models.CharField(blank=True, max_length=100, null=True)),
                ('new_cases', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
